"""Initial migration

Revision ID: 679cf6a232e2
Revises: 0e7b618ba0ff
Create Date: 2024-09-08 23:04:13.264515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '679cf6a232e2'
down_revision = '0e7b618ba0ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_restaurant', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_restaurant', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
